export const orderingCopy = {
  fr: {
    order: "Commander en ligne", add: "Ajouter au panier", added: "Ajouté", cart: "Panier", empty: "Votre panier est vide.", browse: "Découvrir la carte", checkout: "Passer la commande", remove: "Retirer", clear: "Vider le panier", quantity: "Quantité", notes: "Notes pour ce plat", subtotal: "Sous-total", deliveryFee: "Livraison", total: "Total", serving: "Portion", pickup: "À emporter", delivery: "Livraison", name: "Nom", phone: "Téléphone", email: "E-mail (facultatif)", street: "Adresse", postalCode: "Code postal", city: "Ville", instructions: "Instructions de livraison (facultatif)", orderNotes: "Notes de commande (facultatif)", place: "Confirmer la commande", sending: "Envoi en cours…", confirmation: "Commande reçue", number: "Commande", status: "Statut", new: "Nouvelle", pending: "Paiement en attente", paymentNote: "Aucun paiement en ligne n’est prélevé. Le paiement reste à effectuer auprès du restaurant.", loading: "Chargement…", retry: "Réessayer", unavailable: "La commande est momentanément indisponible. Réessayez ou contactez le restaurant.", invalid: "Vérifiez les coordonnées, les quantités et la longueur des notes.", itemUnavailable: "Un plat n’est plus disponible ou son prix a changé. Vérifiez votre panier.", conflict: "Cette demande a déjà été utilisée. Vérifiez votre confirmation avant de réessayer.", minimum: "Le minimum de commande pour cette zone n’est pas atteint.", zone: "Vérifiez que votre ville et votre code postal correspondent à la zone choisie.", deliveryDisabled: "La livraison est momentanément indisponible.", region: "Zone de livraison", choose: "Choisir une zone", minimumLabel: "Minimum", customer: "Vos coordonnées", noReceipt: "Aucune confirmation dans cet onglet.", storage: "Le stockage du navigateur est indisponible. Le panier sera conservé uniquement pendant cette visite.", unavailableItem: "Plat indisponible — retirez-le pour continuer.", back: "Retour au panier", refresh: "Actualiser les prix", unit: "Prix unitaire", decrease: "Diminuer la quantité", increase: "Augmenter la quantité", cartLimit: "Limite atteinte : 20 par plat, 100 articles ou 50 lignes.", pricesNote: "Les prix et la disponibilité sont vérifiés lors de la commande.",
  },
  en: {
    order: "Order online", add: "Add to cart", added: "Added", cart: "Cart", empty: "Your cart is empty.", browse: "Browse the menu", checkout: "Checkout", remove: "Remove", clear: "Clear cart", quantity: "Quantity", notes: "Item notes", subtotal: "Subtotal", deliveryFee: "Delivery fee", total: "Total", serving: "Serving", pickup: "Pickup", delivery: "Delivery", name: "Name", phone: "Phone", email: "Email (optional)", street: "Street address", postalCode: "Postal code", city: "City", instructions: "Delivery instructions (optional)", orderNotes: "Order notes (optional)", place: "Place order", sending: "Placing order…", confirmation: "Order received", number: "Order", status: "Status", new: "New", pending: "Payment pending", paymentNote: "No online payment is taken. Payment remains due to the restaurant.", loading: "Loading…", retry: "Try again", unavailable: "Ordering is temporarily unavailable. Try again or contact the restaurant.", invalid: "Check your contact details, quantities and note lengths.", itemUnavailable: "An item is unavailable or its price changed. Review your cart.", conflict: "This request has already been used. Check your confirmation before retrying.", minimum: "The minimum order for this delivery area has not been reached.", zone: "Check that your city and postal code match the selected delivery area.", deliveryDisabled: "Delivery is temporarily unavailable.", region: "Delivery area", choose: "Choose an area", minimumLabel: "Minimum", customer: "Your details", noReceipt: "No order confirmation in this tab.", storage: "Browser storage is unavailable. Your cart will only be kept during this visit.", unavailableItem: "Unavailable item — remove it to continue.", back: "Back to cart", refresh: "Refresh prices", unit: "Unit price", decrease: "Decrease quantity", increase: "Increase quantity", cartLimit: "Limit reached: 20 per item, 100 items or 50 lines.", pricesNote: "Prices and availability are checked when you place the order.",
  },
  de: {
    order: "Online bestellen", add: "In den Warenkorb", added: "Hinzugefügt", cart: "Warenkorb", empty: "Ihr Warenkorb ist leer.", browse: "Speisekarte ansehen", checkout: "Zur Kasse", remove: "Entfernen", clear: "Warenkorb leeren", quantity: "Menge", notes: "Hinweise zum Gericht", subtotal: "Zwischensumme", deliveryFee: "Liefergebühr", total: "Gesamt", serving: "Portion", pickup: "Abholung", delivery: "Lieferung", name: "Name", phone: "Telefon", email: "E-Mail (optional)", street: "Straße und Hausnummer", postalCode: "Postleitzahl", city: "Ort", instructions: "Lieferhinweise (optional)", orderNotes: "Bestellhinweise (optional)", place: "Bestellung aufgeben", sending: "Bestellung wird gesendet…", confirmation: "Bestellung eingegangen", number: "Bestellung", status: "Status", new: "Neu", pending: "Zahlung ausstehend", paymentNote: "Es wird keine Online-Zahlung eingezogen. Die Zahlung erfolgt beim Restaurant.", loading: "Wird geladen…", retry: "Erneut versuchen", unavailable: "Bestellungen sind momentan nicht möglich. Versuchen Sie es erneut oder kontaktieren Sie das Restaurant.", invalid: "Prüfen Sie Ihre Kontaktdaten, Mengen und die Länge der Hinweise.", itemUnavailable: "Ein Gericht ist nicht mehr verfügbar oder der Preis hat sich geändert. Prüfen Sie den Warenkorb.", conflict: "Diese Anfrage wurde bereits verwendet. Prüfen Sie die Bestätigung vor einem neuen Versuch.", minimum: "Der Mindestbestellwert für dieses Liefergebiet ist noch nicht erreicht.", zone: "Prüfen Sie, ob Ort und Postleitzahl zum gewählten Liefergebiet passen.", deliveryDisabled: "Lieferungen sind momentan nicht möglich.", region: "Liefergebiet", choose: "Gebiet wählen", minimumLabel: "Mindestbestellwert", customer: "Ihre Angaben", noReceipt: "Keine Bestellbestätigung in diesem Tab.", storage: "Browserspeicher ist nicht verfügbar. Der Warenkorb bleibt nur während dieses Besuchs erhalten.", unavailableItem: "Nicht verfügbar — zum Fortfahren entfernen.", back: "Zurück zum Warenkorb", refresh: "Preise aktualisieren", unit: "Stückpreis", decrease: "Menge verringern", increase: "Menge erhöhen", cartLimit: "Limit erreicht: 20 pro Gericht, 100 Artikel oder 50 Positionen.", pricesNote: "Preise und Verfügbarkeit werden beim Bestellen geprüft.",
  },
};

export const orderStatusCopy = {
  fr: { new: "Nouvelle", accepted: "Acceptée", preparing: "En préparation", ready: "Prête", completed: "Terminée", rejected: "Refusée", cancelled: "Annulée" },
  en: { new: "New", accepted: "Accepted", preparing: "Preparing", ready: "Ready", completed: "Completed", rejected: "Rejected", cancelled: "Cancelled" },
  de: { new: "Neu", accepted: "Angenommen", preparing: "In Zubereitung", ready: "Bereit", completed: "Abgeschlossen", rejected: "Abgelehnt", cancelled: "Storniert" },
};
